services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secrethouse
      MYSQL_USER: secrethouse
      MYSQL_PASSWORD: secrethouse
      MYSQL_DATABASE: secrethouse
    networks:
      - secrethouse-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - secrethouse-network

networks:
   secrethouse-network:
