services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secrethouse
      MYSQL_USER: secrethouse
      MYSQL_DATABASE: secrethouse
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080